### ISSUE TITLE
Death messages

### ISSUE THREAD

**Issue by stevoism** [nextinfinity/SuperCraftBros#25]
Is there a way to add better death messages. There is no credit to the killer when falling into the void. If this could be altered to keep track of kills as well as the lives left then you could make the end more like SSB wherelast alive ended the game but most kills actually won.

**Comment by nextinfinity** [comment]
I won't say it's impossible but SCB currently just uses default Minecraft messages, in order to add something as simple as who knocked a person off I'd have to add a custom death interpreter, and even then you might end up losing more functionality than what you gain. May consider taking this on at a later date, but it's also worth considering that a number of players may prefer the last man standing style of victory.

**Comment by nextinfinity** [comment]
Closing this one as it is low priority and would take a lot of effort. If someone would like to assist please let me know and I'll reopen it, otherwise it will remain a long term goal.
